In [1]:
import util
import zMCST
from importlib import reload

DATA = util.unpickle('data')
len(DATA)
import data
reload(data)
dl = data.dataloader(DATA,10,100)
b = next(dl)
b.keys(),len(DATA)

(dict_keys(['z', 'inp', 'plyr', 'pi']), 9000)

In [2]:
rn.keys()


NameError: name 'rn' is not defined

In [ ]:
zMCST.UCB1

In [8]:
rn = util.unpickle('rootnode')
rn['C'].keys()
import zMCST
reload(zMCST)

def stat(node):
    
    for k,v in rn['C'].items():
        print(k, v['n'],v['q'], v['w'] )
    print(zMCST.UBC(node, range(9) ) )
        
stat(rn)

8 3008 0.0021226713041037426 6.3849952827440575
3 877 0.00101679944069026 0.891733109485358
4 558 0.0021805981266742915 1.2167737546842545
6 355 0.00042940856508490903 0.1524400406051427
7 298 -0.0008289805354062943 -0.2470361995510757
5 406 0.0018976487453311241 0.7704453906044364
2 281 -0.00032311477748100443 -0.09079525247216225
0 175 -0.0009322811583323138 -0.16314920270815492
1 41 -0.001287351680419794 -0.05278141889721155
[tensor(0.0042), tensor(0.0042), tensor(0.0039), tensor(0.0032), tensor(0.0026), tensor(0.0028), tensor(0.0035), tensor(0.0041), tensor(0.0012)]


In [6]:
import AI
reload(AI)
F = AI.model(3)
AI.train(F, DATA, 20)

KeyboardInterrupt: 

In [124]:
b['pi'].shape

torch.Size([10, 9])

In [6]:
import util
import zMCST
from importlib import reload
import numpy as np


print(len(DATA))
def show_board(board):
    key = {2:'.', 1:'1', 0:'0'}              
    a,b = board.shape
    for i in range(a):
        line = ' '.join( [ key[x] for x in board[i]])
        print(line)
        
def roundlist(L): return [ round(l,3) for l in L]

9000


In [7]:
from IPython.display import display,clear_output
import ipywidgets as widgets
P = widgets.Button(description="Prev")
N = widgets.Button(description="Next")
DATA = util.unpickle('data')
print(len(DATA))

i = 0
def NEXT(b):
    global i
    i+=1
    with out:
        clear_output()
        pprint(DATA[i])
def prev(b): 
    global i
    i-=1
    with out: 
        clear_output()
        pprint(DATA[i])
    
def pprint(DATAi):
    global i
    print(i)
    show_board(DATAi['board'])
    print('PLY:', DATAi['plyr'], 'Z:', DATAi['z'])
    pi = np.array( roundlist(DATAi['pi']) ).reshape(3,3)
    
    ubc = np.array( roundlist(DATAi['ubc']) ).reshape(3,3)
    print(ubc, 'UBC')
    Cw = np.array(DATAi['Cw']).reshape(3,3)
    Cn = np.array(DATAi['Cn']).reshape(3,3)
    Cv = np.array(DATAi['Cv']).reshape(3,3)
    print( Cw, 'CW')
    print( Cn, 'CN')
    print( Cv, 'CV')
    P = np.array( roundlist(DATAi['P']) ).reshape(3,3)
    print( P, 'P')
    print(pi, 'pi')
    
out = widgets.Output()

display(widgets.HBox((P,N)))
display(out)

P.on_click(prev)
N.on_click(NEXT)

9000


Output()

In [ ]:
DATA[-4]['node']['C']

In [17]:
import AI
import testmodel
reload(testmodel)
reload(AI)
import torch
F = AI.model(3).eval()
F.load_state_dict( torch.load('models/10.pth'))

<All keys matched successfully>

In [21]:
x = torch.rand(1,3,3,3)
from data import inp2boards
b = ['1 1',
     ' 0 ',
     '  0' ]

#b = [ l.split(' ') for l in b]
def int2str(c):
    if c=='0': return 0
    if c=='1': return 1
    if c==' ': return 2
b = [ [ int2str(c) for c in l] for l in b]

    
inp = inp2boards([b])
def plyr2board(inp): 
    plyrs = []
    for binp in inp:
        if binp[0].sum()==binp[1].sum(): plyrs.append(0)
        else: plyrs.append(1)
    return plyrs
print('plyr', plyr2board(inp))
                 
P,v = F(inp,plyr2board(inp))
print( show_board(np.array(b) ) )
#print(inp2boards([b])[:,:2])

P = roundlist(P[0].detach().numpy())
P = torch.tensor(P)
P.reshape(3,3).detach().numpy(), v

plyr [0]
1 . 1
. 0 .
. . 0
None


(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 tensor([-0.0150], grad_fn=<ViewBackward>))

In [20]:

inp2boards([b])

tensor([[[[0., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 1.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 1., 0.],
          [1., 0., 1.],
          [1., 1., 0.]]]])

In [396]:
b2 = [ [ int2str(c) for c in l] for l in b2]
inp2boards([b2])

tensor([[[[1., 1., 1.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 1.],
          [0., 1., 1.]],

         [[0., 0., 0.],
          [1., 1., 0.],
          [1., 0., 0.]]]])